AWSTemplateFormatVersion: 2010-09-09
Description: ServerlessPizza Code Pipeline Template

Parameters:
  ModuleName:
    Description: The name of the module to create the pipeline for
    Type: String
  GitHubToken:
    Description: The GitHub Personal Access Token to use
    Type: String

Resources:
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Join
        - '-'
        - - 'serverlesspizza'
          - !Ref ModuleName
          - 'pipeline'
      RoleArn:
        Fn::ImportValue:
          !Sub "PipeLineRoleArn"
      ArtifactStore:
        Type: S3
        EncryptionKey:
          Id:
            Fn::ImportValue: "KMSKeyArn"
          Type: KMS
        Location:
          Fn::ImportValue: "ArtifactBucket"
      Stages:
        -
          Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: 1
                Provider: GitHub
              OutputArtifacts:
                - Name: SourceArtifact
              Configuration:
                Owner: serverlesspizza
                Repo: !Ref ModuleName
                Branch: master
                OAuthToken: !Ref GitHubToken
              RunOrder: 1
        -
          Name: Build-dev
          Actions:
            - Name: Build
              InputArtifacts:
                - Name: SourceArtifact
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              Configuration:
                ProjectName: BuildProject
                EnvironmentVariables: '[{"name":"REACT_APP_ENVIRONMENT","value":"dev","type":"PLAINTEXT"},{"name":"REACT_APP_USER_POOL_ID","value":"/serverlesspizza/cognito/user_pool_id/dev","type":"PARAMETER_STORE"},{"name":"REACT_APP_USER_POOL_WEB_CLIENT_ID","value":"/serverlesspizza/cognito/user_pool_web_client_id/dev","type":"PARAMETER_STORE"},{"name":"REACT_APP_IDENTITY_POOL_ID","value":"/serverlesspizza/cognito/identity_pool_id/dev","type":"PARAMETER_STORE"}]'
              OutputArtifacts:
                - Name: BuildDevArtifact
              RunOrder: 1
        -
          Name: Deploy-dev
          Actions:
            - Name: BuildChangeSet
              InputArtifacts:
                - Name: BuildDevArtifact
                - Name: SourceArtifact
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: CloudFormation
              Configuration:
                ActionMode: CHANGE_SET_REPLACE
                StackName: !Sub 'serverlesspizza-${ModuleName}-stack-dev'
                ChangeSetName: !Sub 'serverlesspizza-${ModuleName}-changeset-dev'
                Capabilities: CAPABILITY_IAM
                TemplatePath: SourceArtifact::cfn-web.yml
                RoleArn:
                  Fn::ImportValue: "DevCloudFormationDeployerRole"
                ParameterOverrides: '{"Environment": "dev"}'
              RunOrder: 1
              RoleArn:
                Fn::ImportValue: "DevDevOpsAccountCodePipelineCFRole"
            - Name: ExecuteChangeSet
              InputArtifacts:
                - Name: BuildDevArtifact
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: CloudFormation
              Configuration:
                ActionMode: CHANGE_SET_EXECUTE
                RoleArn:
                  Fn::ImportValue: "DevCloudFormationDeployerRole"
                StackName: !Sub 'serverlesspizza-${ModuleName}-stack-dev'
                ChangeSetName: !Sub 'serverlesspizza-${ModuleName}-changeset-dev'
              RunOrder: 2
              RoleArn:
                Fn::ImportValue: "DevDevOpsAccountCodePipelineCFRole"
            - Name: DeployContent
              InputArtifacts:
                - Name: BuildDevArtifact
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: S3
              Configuration:
                BucketName: 'dev.serverlesspizza.com'
                Extract: true
              RunOrder: 3
              RoleArn:
                Fn::ImportValue: "DevDevOpsAccountCodePipelineCFRole"
        -
          Name: Approve-prod-deployment
          Actions:
            - Name: ApprovalRequired
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Version: 1
                Provider: Manual
              RunOrder: 1
        -

          Name: Build-prod
          Actions:
            - Name: Build
              InputArtifacts:
                - Name: SourceArtifact
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              Configuration:
                ProjectName: BuildProject
                EnvironmentVariables: '[{"name":"REACT_APP_ENVIRONMENT","value":"prod","type":"PLAINTEXT"},{"name":"REACT_APP_USER_POOL_ID","value":"/serverlesspizza/cognito/user_pool_id/prod","type":"PARAMETER_STORE"},{"name":"REACT_APP_USER_POOL_WEB_CLIENT_ID","value":"/serverlesspizza/cognito/user_pool_web_client_id/prod","type":"PARAMETER_STORE"},{"name":"REACT_APP_IDENTITY_POOL_ID","value":"/serverlesspizza/cognito/identity_pool_id/prod","type":"PARAMETER_STORE"}]'
              OutputArtifacts:
                - Name: BuildProdArtifact
              RunOrder: 1
        -
          Name: Deploy-prod
          Actions:
            - Name: BuildChangeSet
              InputArtifacts:
                - Name: BuildProdArtifact
                - Name: SourceArtifact
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: CloudFormation
              Configuration:
                ActionMode: CHANGE_SET_REPLACE
                StackName: !Sub 'serverlesspizza-${ModuleName}-stack-prod'
                ChangeSetName: !Sub 'serverlesspizza-${ModuleName}-changeset-prod'
                Capabilities: CAPABILITY_IAM
                TemplatePath: SourceArtifact::cfn-web.yml
                RoleArn:
                  Fn::ImportValue: "ProdCloudFormationDeployerRole"
                ParameterOverrides: '{"Environment": "prod"}'
              RunOrder: 1
              RoleArn:
                Fn::ImportValue: "ProdDevOpsAccountCodePipelineCFRole"
            - Name: ExecuteChangeSet
              InputArtifacts:
                - Name: BuildProdArtifact
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: CloudFormation
              Configuration:
                ActionMode: CHANGE_SET_EXECUTE
                RoleArn:
                  Fn::ImportValue: "ProdCloudFormationDeployerRole"
                StackName: !Sub 'serverlesspizza-${ModuleName}-stack-prod'
                ChangeSetName: !Sub 'serverlesspizza-${ModuleName}-changeset-prod'
              RunOrder: 2
              RoleArn:
                Fn::ImportValue: "ProdDevOpsAccountCodePipelineCFRole"
            - Name: DeployContent
              InputArtifacts:
                - Name: BuildProdArtifact
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: S3
              Configuration:
                BucketName: 'prod.serverlesspizza.com'
                Extract: true
              RunOrder: 3
              RoleArn:
                Fn::ImportValue: "ProdDevOpsAccountCodePipelineCFRole"
